name: Run MyPy Lint
description: "Runs MyPy as a lint step and reports it as a Check to GitHub"
inputs:
  tag:
    required: true
    description: "The image on which to run mypy. This is expected to be a django image with pip and other dependencies already installed"
  image_name:
    required: true
    default: "ghcr.io/spotdraft/django-rest-api"
    description: "Full docker image path excluding tag"
runs:
  using: "composite"
  steps:
    - name: MyPy lint
      shell: bash
      run: |
        cd /app
        ./run_mypy.sh
