name: Push Slack Message
description: "Push Message to slack"
inputs:
  SLACK_WEBHOOK:
    required: true
    description: "Slack webhook url"
  SLACK_ICON:
    required: true
    description: "Icon to show in slack message"
  SLACK_MESSAGE:
    required: true
    description: "Slack Message body"
  SLACK_TITLE:
    required: true
    description: "Slack Message Title"
  SLACK_USERNAME:
    required: true
    description: "User name which shows in slack message"
runs:
  using: "composite"
  steps:
    - name: Slack Notification
      uses: SpotDraft/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: ${{ inputs.SLACK_ICON }}
        SLACK_MESSAGE: ${{ inputs.SLACK_MESSAGE }}
        SLACK_TITLE: ${{ inputs.SLACK_TITLE }}
        SLACK_USERNAME: ${{ inputs.SLACK_USERNAME }}
