name: Generate New Tag
description: "Generate new tag based on current tag and release branch"
inputs:
  qa-tag:
    required: true
    description: "QA tag which has to be promoted to prod"
  release-branch:
    required: true
    description: "QA release branch which we are promoting"
outputs:
  new_tag:
    description: "The new tag which was generated"
    value: ${{ steps.generate-tag.outputs.new_tag }}
runs:
  using: "composite"
  steps:
    - name: Generate New PROD Tag
      id: generate-tag
      shell: bash
      run: |
        echo ${{ inputs.release-branch }}
        release_date=`cut -d'-' -f2 <<< ${{ inputs.release-branch }}`
        search_key=prod_$release_date
        git for-each-ref --sort=creatordate --format '%(refname) %(creatordate)' refs/tags | grep $search_key > tags.txt
        if [ $? -eq 0 ]
        then
            current_latest_tag_with_datetime=`tail -1 tags.txt | xargs`
            current_latest_tag_ref=`cut -d' ' -f1 <<< $current_latest_tag_with_datetime`
            current_latest_tag=`cut -d'/' -f3 <<< $current_latest_tag_ref`
            echo  "Current tag: $current_latest_tag"
            count=`echo $current_latest_tag | grep -o "_" | wc -l`
            if [ $count == 1 ]
            then
                echo "old tag is $current_latest_tag"
                new_tag="${current_latest_tag}_RC1"
                echo "New Prod tag is: $new_tag"
            else 
                if [ $count == 2 ]
                then
                    echo "old tag is $current_latest_tag"
                    f1=`cut -d'_' -f1 <<< $current_latest_tag` 
                    f2=`cut -d'_' -f2 <<< $current_latest_tag` 
                    f3=`cut -d'_' -f3 <<< $current_latest_tag` 
                    rc_number=`echo $f3 | grep -Eo '[0-9]+$'`
                    rc_number_new=$((rc_number+1))
                    new_tag=${f1}_${f2}_RC${rc_number_new}
                    echo "New Prod tag is: $new_tag"
                fi
            fi
        else
            new_prod_tag=prod_$release_date
            echo "New prod tag: $new_prod_tag"
        fi
        echo "::set-output name=new_tag::$new_tag"
