name: Get Previous Tag
description: "Get previoud tag of supplied tag"
inputs:
  tag:
    required: true
    description: "Release branch name on which tag has to be created"
outputs:
  previous_tag:
    description: "The docker image tag as generated during build"
    value: ${{ steps.previous-tag.outputs.previous_tag }}
runs:
  using: "composite"
  steps:
    - name: get previous tag
      id: previous-tag
      shell: bash
      run: |
        export TERM=xterm-color
        current_tag=${{ inputs.tag }}
        echo "Current Tag: $current_tag"
        release_date=`cut -d'-' -f2 <<< $current_tag`
        current_release_branch=release-$release_date
        echo "Current release branch: $current_release_branch"
        git branch -r  | grep release | grep -vE $current_release_branch > remote-branches.txt
        previous_release_branch=`tail -1 remote-branches.txt | xargs`
        previous_release_date=`cut -d'-' -f2 <<< $previous_release_branch`
        echo "Previous release branch: $previous_release_branch"
        count=`echo $current_tag | grep -o "_" | wc -l`
        if [ $count == 1 ]
        then
            environment=`cut -d'_' -f1 <<< $current_tag`
            serarch_key=${environment}_${previous_release_date}
            git for-each-ref --sort=creatordate --format '%(refname) %(creatordate)' refs/tags | grep $search_key > tags.txt
            previous_tag_with_datetime=`tail -1 tags.txt | xargs`
            previous_tag_ref=`cut -d' ' -f1 <<< $previous_tag_with_datetime`
            previous_tag=`cut -d'/' -f3 <<< $previous_tag_ref`
            echo "Previous tag is $previous_tag"
        else 
            if [ $count == 2 ]
            then
                environment=`cut -d'_' -f1 <<< $current_tag`
                serarch_key=${environment}_${release_date}
                git for-each-ref --sort=creatordate --format '%(refname) %(creatordate)' refs/tags | grep $search_key > tags.txt
                previous_tag_with_datetime=`tail -2 tags.txt | xargs`
                previous_tag_ref=`cut -d' ' -f1 <<< $previous_tag_with_datetime`
                previous_tag=`cut -d'/' -f3 <<< $previous_tag_ref`
                echo "Previous tag is $previous_tag"
            fi
        fi
        echo "::set-output name=previous_tag::$previous_tag"
