name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: github-actions-test
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set permission
      run: chmod +x ./scripts/build-image.sh
    - name: build-image
      run: ./scripts/build-image.sh
    - name: Log in to registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build branch image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/diyalab/django-rets-api:${{ github.ref_name }}
  purge-image:
      name: Delete image from ghcr.io
      runs-on: ubuntu-latest
      steps:
        - name: Delete image
          uses: bots-house/ghcr-delete-image-action@v1.0.0
          with:
            # NOTE: at now only orgs is supported
            owner: diyalab
            name: django-rets-api
            # NOTE: using Personal Access Token
            token: ${{ secrets.PAT }}
            tag: ${{ github.ref_name }}
