name: Create Release
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Environment Name
        options:
          - QA
          - PROD
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: make release branch name
        id: release-name
        shell: bash
        run: |
          date=`echo $(date '+%Y-%m-%d') | tr -d '-'`
          release-name=release-$date
          echo "::set-output name=release::$release-name"

      - name: create-release-barnch
        run: echo ${{ steps.release-name.outputs.release }}
      # - name: Initialize mandatory git config
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email noreply@github.com
