name: Create Release
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Environment Name
        options:
          - QA
          - PROD
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: create-release-barnch
        run: git checkout -b release-20220609
      # - name: Initialize mandatory git config
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email noreply@github.com
