name: "pr test1"
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: diyalab/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'run test'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        status: queued
        conclusion: ${{ job.status }}
        output: |
          {"summary": "tests started"}
      - uses: actions/checkout@v3
        if: steps.check.outputs.triggered == 'true'
      - run: 'echo Found it! siva'
        if: steps.check.outputs.triggered == 'true'
      - run: |
          cat test.js
        if: steps.check.outputs.triggered == 'true'