name: workflow for PR
on:
  pull_request:
    types: [opened, labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          labels: |
            test-passed
