name: "pr test1"
on:
  pull_request:
    types: [opened, labeled]
  # label:
  #   types: [created]
  # issue_comment:
  #   types: [created]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "siva"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LouisBrunner/checks-action@v1.1.1
      # if: ${{ github.event.label.name != 'test' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Unit tests
        conclusion: neutral
    - name: Run a one-line script
      if: ${{ github.event.label.name == 'test' }}
      run: echo Hello, world!