name: "pr test1"
on:
  pull_request:
    types: [opened]
    types: [ labeled ]
  # issue_comment:
  #   types: [created]
jobs:
  build:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!