name: "Label stale PR's"
on:
  schedule:
    - cron: '*/5  * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-label: 'stale'
          days-before-stale: 1