name: Workflow for New Tag
on:
  create:
    tags:
      - qa_*
jobs:
  get-previous-tag:
    runs-on: ubuntu-latest
    outputs:
      previous_tag: ${{ steps.previous-tag.outputs.previous_tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: get previous tag
        id: previous-tag
        uses: ./.github/get_previous_tag
        with:
          tag: ${{ env.RELEASE_VERSION }}
      - name: echo
        run: echo ${{ steps.previous-tag.outputs.previous_tag }}