on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  ${{ inputs.tags }} 
