name: ci

on:
  push:

jobs:
  build:
    name: Build PHP Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov

      - name: PHPUnit
        id: phpunit
        continue-on-error: true
        run: ./vendor/bin/phpunit --coverage-text

      - name: Report PHPUnit Conclusion
        if: always()
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: phpunit
          conclusion: ${{ steps.phpunit.outcome }}