name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: [high-mem]
    steps:
      - uses: actions/checkout@master
      - name: Build and push
        run: docker build -t test .
  # docker:
  #   runs-on: [high-mem]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: sleep
  #       run: sleep 200
  # docker1:
  #   runs-on: [high-mem]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: sleep
  #       run: sleep 200
      