name: ci

on:
  push:

jobs:
  build:
    steps:
      - name: Report PHPUnit Starting
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: phpunit
          status: in_progress