name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: [self-hosted, low-mem]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: sleep
        run: sleep 100
  docker1:
    runs-on: [self-hosted, high-mem]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: sleep
        run: sleep 100
      