name: "test"
on:
  push:
    branches:
      - 'main'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Changelog
    steps:
      # - name: Set Version
      #   run: echo ::set-env name=VERSION::1.1.1
      # To use this repository's private action, you must check out the repository
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: checkout qa tag
        run: |
          git checkout qa_20220614_RC34 
          git tag prod_20220614_RC34 
          git push --tags