name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: [high-mem]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: sleep
        run: sleep 200
  docker1:
    runs-on: [high-mem]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: sleep
        run: sleep 200
      